### ISSUE TITLE
training configuration question

### ISSUE THREAD

**Issue by yuraSomatic** [gasparramoa/DeepDoors2#1]
What optimizer, did you use? Did you freeze any of GoogleNet / AlexNet layers ?
Asking, because can't find this in your paper. 
https://www.researchgate.net/publication/343657620_Real-Time_2D-3D_Door_Detection_and_Classification_on_Jetson_Nano

**Comment by gasparramoa** [comment]
Dear @yuraSomatic,

Sorry for the late reply but, my life has been a rollercoaster.
I used the same configurations as the repo **_jetson_inference_** used (ImageNet), so it would be easier to re-create my method.

I will leave you the link for the _ImageNet_ tutorial: [link](https://github.com/dusty-nv/jetson-inference/blob/master/docs/imagenet-console.md)

And the **_DIGITS_** tutorial, which was the platform that I used for training, you have there the **two models** of _GoogleNet_ and _AlexNet_ that I used: [link](https://github.com/dusty-nv/jetson-inference/blob/master/docs/imagenet-training.md#creating-image-classification-model-with-digits)






Don't hesitate to contact me!
Gaspar

P.S. At the time I developed this project the repo was not as big as it is now, so you should get plenty of new neural networks in _TensorRT_ format to use.
